version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn recetapp.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/recetapp/web/staticfiles
      - media_volume:/home/recetapp/web/mediafiles
    expose:
      - 8000
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/recetapp/web/staticfiles
      - media_volume:/home/recetapp/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: