# Generated by Django 3.0.5 on 2020-05-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20200503_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='main_image_name',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cover_picture',
            field=models.ImageField(default='', upload_to='photos'),
            preserve_default=False,
        ),
    ]
